"""
Konversi Neue Montreal (.ttf) menjadi .woff2 yang di-self-host, plus modul base64
yang dipakai untuk merender OG image di server.

Jalankan ulang bila file font sumber berubah:

    python scripts/build-font-assets.py

Butuh: pip install fonttools brotli
"""

import base64
import os
import pathlib
import sys

from fontTools.ttLib import TTFont

SOURCE_DIR = os.environ.get(
    "NEUE_MONTREAL_DIR", r"C:\Users\User\Downloads\NEUE MONTREAL"
)
FACES = (("NeueMontreal-Regular", 400), ("NeueMontreal-Medium", 500))
ROOT = pathlib.Path(__file__).resolve().parent.parent


def main() -> int:
    out_dir = ROOT / "public" / "fonts"
    out_dir.mkdir(parents=True, exist_ok=True)

    for name, weight in FACES:
        source = os.path.join(SOURCE_DIR, name + ".ttf")
        if not os.path.exists(source):
            print(f"font sumber tidak ditemukan: {source}", file=sys.stderr)
            return 1
        font = TTFont(source)
        font.flavor = "woff2"
        dest = out_dir / (name + ".woff2")
        font.save(str(dest))
        print(f"{name} (weight {weight}) -> {dest} ({dest.stat().st_size} bytes)")

    # satori (mesin OG image) hanya menerima TTF/OTF, bukan WOFF2.
    ttf_bytes = pathlib.Path(SOURCE_DIR, "NeueMontreal-Medium.ttf").read_bytes()
    encoded = base64.b64encode(ttf_bytes).decode("ascii")
    module = ROOT / "src" / "assets" / "neue-montreal-medium.ts"
    module.parent.mkdir(parents=True, exist_ok=True)
    module.write_text(
        "// Auto-generated by scripts/build-font-assets.py. Neue Montreal Medium, base64 TTF.\n"
        "// Dipakai hanya untuk merender OG image di server (satori butuh TTF, bukan WOFF2).\n"
        "export const NEUE_MONTREAL_MEDIUM_TTF_BASE64 =\n"
        f'  "{encoded}";\n',
        encoding="utf-8",
    )
    print(f"base64 module -> {module}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
